// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZz8nNsJQOTl5L-HwV4-ggewU5Purgtw',
    appId: '1:505961183988:web:71beba1f31613e78b8fca1',
    messagingSenderId: '505961183988',
    projectId: 'belajarfirebase-b3d4f',
    authDomain: 'belajarfirebase-b3d4f.firebaseapp.com',
    storageBucket: 'belajarfirebase-b3d4f.appspot.com',
    measurementId: 'G-5KYFZ3BVDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZXz89i8wQ9Xl_MzD-dJ5Td0edSXZShY',
    appId: '1:505961183988:android:10ec0bdd3069bf47b8fca1',
    messagingSenderId: '505961183988',
    projectId: 'belajarfirebase-b3d4f',
    storageBucket: 'belajarfirebase-b3d4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9mpWtf8CXoo6I0R-zkinsZ8oslDiEAo',
    appId: '1:505961183988:ios:57930caae61c5175b8fca1',
    messagingSenderId: '505961183988',
    projectId: 'belajarfirebase-b3d4f',
    storageBucket: 'belajarfirebase-b3d4f.appspot.com',
    iosClientId: '505961183988-90jj1vqfblcesfbd0emfo85iitsjnreo.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh9mpWtf8CXoo6I0R-zkinsZ8oslDiEAo',
    appId: '1:505961183988:ios:57930caae61c5175b8fca1',
    messagingSenderId: '505961183988',
    projectId: 'belajarfirebase-b3d4f',
    storageBucket: 'belajarfirebase-b3d4f.appspot.com',
    iosClientId: '505961183988-90jj1vqfblcesfbd0emfo85iitsjnreo.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekAkhir',
  );
}
